changed is_verified to accept null values
Cloudanix/detect-secrets pull request #8
Opened 2023-07-05 04:24 UTC by geekNero

2023-07-05 17:30 UTC, mpurusottamc commented on detect_secrets/plugins/base.py
> +                    is_verified = None
we should not return None. It should be False. If we are not able to verify, then it should be False.

2023-07-05 17:31 UTC, mpurusottamc requested changes
let's not return None for is verified.

2023-07-06 04:21 UTC, geekNero commented on detect_secrets/plugins/base.py
> +                    is_verified = None
The none represents that the verification failed and we have no information whether the secret is valid or not

2023-07-06 06:27 UTC, mpurusottamc approved these changes
makes sense now.

2023-07-06 06:27 UTC, merged